version: '2.1'

services:
    db:
        image: postgres:12.0
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: odoo
            POSTGRES_PASSWORD: odoo
        volumes:
            - pgsql:/var/lib/postgresql/data:rw,Z

    odoo:
        image: odoo:13.0
        restart: always
        volumes:
            - odoo:/var/lib/odoo:rw,z
            - ./:/mnt/extra-addons:ro,z
            - /home/abdalla/Documents/odoo/source_code/enterprise:/mnt/enterprise-addons:ro,z
            - .:/etc/odoo:ro,z
        ports:
            - "8069:8069"
        depends_on:
            - db
        command: odoo --dev=all

volumes:
    pgsql:
    odoo:
